discord:
  token: ${DISCORD_TOKEN:You can obtain a valid bot token at https://discord.com/developers/applications}
  development-guild-id: 932728712355512331

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/replies}
    username: ${DATABASE_USERNAME:replies}
    password: ${DATABASE_PASSWORD:replies}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
